### PR TITLE
update for jedi v0.18.+

### LINKED ISSUE #452: Autocomplete not working with Jedi 0.18 and Miniconda
### Steps to Reproduce

I installed the autocomplete-python package with my Python 3.8.8 Miniconda installation with Jedi 0.18 (everything is updated).
The package folders get recognized correctly with the Miniconda folders, but it gives an error and the suggestions don't work.

**Actual behavior:**

Looks like this error originated from Jedi. Please do not report such issues in autocomplete-python issue tracker. Report them directly to Jedi. Turn off outputProviderErrors setting to hide such errors in future. Traceback output:

```py
Traceback (most recent call last):
  File "C:\Users\aless\.atom\packages\autocomplete-python\lib/completion.py", line 378, in watch
    self._process_request(request)
  File "C:\Users\aless\.atom\packages\autocomplete-python\lib/completion.py", line 338, in _process_request
    script = jedi.api.Script(
TypeError: __init__() got an unexpected keyword argument 'source'
```

### LINKED ISSUE #462: autocomplete-python isn't working with python 3.10 and jedi 0.18
I downloaded Jedi and Python 3.10 and autocomplete-python isn't working...
Even after configuration it still doesn't work.
Any help would be appreciated...
Screenshot (40)

### PR DESCRIPTION
**Pull request by jrobinson3k1**
Running any version of jedi above 0.17 causes this plugin to fail. Removed previously deprecated code that was ultimately removed in jedi v0.18.0.

For fixing a local installation of the 1.17.0 version of autocomplete-python published to Atom, replace `%UserProfile%\.atom\packages\autocomplete-python\lib\completion.py` (Linux/Mac should be `~/.atom/packages/autocomplete-python/lib/completion.py`) with the file in this PR.

Fixes #462, fixes #452

### CODE REVIEW

**Comment by sadovnychyi** [comment]
Hey, thanks.

I'm not using Atom anymore and this package is very outdated – everybody uses language servers nowadays.

I did merge your change and pushed a new release, but unit tests are broken (before your change, not your fault) for me so I couldn't validate anything.

What I did was:

```bash
brew install --cask atom
npm install
apm install
apm test (failed)
apm publish
```

Apologies if I broke something with this.
